apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{.Values.pv.name}}
spec:
  capacity:
    storage: {{.Values.pv.storage}}
  accessModes:
  - ReadWriteMany
  nfs:
    path: "{{.Values.nfs.path}}"
    server: "{{.Values.nfs.serverIP}}"
  persistentVolumeReclaimPolicy: Retain
